id: D18FF1457
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T14:00:53+00:00'
last_modified: '2022-05-29T08:18:37.019648+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8a60:
      image_group_id: I1PD95920
      title: རྣམ་བཤད་བསྡུ་བ།
      total_pages: 1529
      order: 75
      base_file: 8a60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
