id: P9B918949
initial_creation_type: ocr
source_metadata:
  volumes:
    d977e22ff92b455f9a672161269e0b82:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣམ་བཤད་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
